
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>无标题文档</title>
</head>

<body>
			<table width='250px' height='380px' >
			  <tr>
				<td width='65px'><img src='../model/sketch_png.php?msg=ABCDEFG&rot=90&size=20'  > </td>
				<td width='65px'><img src='../model/sketch_png.php?msg=234555555555555555&rot=90&size=20' > </td>
				<td width='65px'><img src='../model/sketch_png.php?msg=2013-12-13&rot=90&size=20' > </td>
			  </tr>
			</table>

</body>
</html>